spring.application.name=payment-service
spring.config.import=configserver:

# Port (0 = random port)
#server.port=
server.port=8085

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecommerce.common.events

spring.kafka.listener.concurrency=4

resilience4j.bulkhead.instances.paymentBulkhead.maxConcurrentCalls=1
resilience4j.bulkhead.instances.paymentBulkhead.maxWaitDuration=0


# expose actuator endpoints
management.endpoints.web.exposure.include=*

# enable prometheus endpoint
management.endpoint.prometheus.enabled=true

# show health details
management.endpoint.health.show-details=always

# add application name in metrics
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
