# ---------------------------------------------------------
# BASIC SETTINGS
# ---------------------------------------------------------

# Application name (MUST match config file name in config-server)
spring.application.name=user-service

# Run on random port (good for scaling multiple instances)
#server.port=
server.port=8081


# ---------------------------------------------------------
# CONFIG SERVER CONNECTION
# ---------------------------------------------------------

# Location of config server
spring.config.import=optional:configserver:http://localhost:8888

# Enable config client
spring.cloud.config.enabled=true


# ---------------------------------------------------------
# EUREKA CONFIGURATION
# ---------------------------------------------------------

# Discovery server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register this service to Eureka
eureka.client.register-with-eureka=true

# Fetch registry
eureka.client.fetch-registry=true


# ---------------------------------------------------------
# ACTUATOR (OPTIONAL BUT GOOD)
# ---------------------------------------------------------

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

logging.level.org.springframework.cloud.config=DEBUG

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}