# ---------------------------------------------------------
# BASIC APPLICATION SETTINGS
# ---------------------------------------------------------

# Name of this application
# Used in logs and identification
spring.application.name=discovery-server

# Port where Eureka server will run
# All services will connect to this port
server.port=8761


# ---------------------------------------------------------
# EUREKA SERVER CONFIGURATION
# ---------------------------------------------------------

# Do NOT register this server as a client
# Because this IS the registry
eureka.client.register-with-eureka=false

# Do NOT fetch registry information
# Since this is the main registry
eureka.client.fetch-registry=false

# Disable self-preservation (optional for development)
# Prevents instance from staying UP when it is actually down
eureka.server.enable-self-preservation=false

# Interval for eviction of dead services (in ms)
# 5000 = 5 seconds (good for development)
#eureka.server.eviction-interval-timer-in-ms=5000

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#eureka.instance.instance-id=${spring.application.name}:${random.value}

# expose actuator endpoints
management.endpoints.web.exposure.include=*

# enable prometheus endpoint
management.endpoint.prometheus.enabled=true

# show health details
management.endpoint.health.show-details=always

# add application name in metrics
management.metrics.tags.application=${spring.application.name}