# ---------------------------------------------------------
# BASIC APPLICATION SETTINGS
# ---------------------------------------------------------

# Name of this service (must be unique)
spring.application.name=config-server

# Port where config server will run
# Clients will connect to this port to fetch config
server.port=8888


# ---------------------------------------------------------
# EUREKA CONFIGURATION
# ---------------------------------------------------------

# URL of Discovery Server
# So config-server can register itself
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register this service in Eureka
eureka.client.register-with-eureka=true

# Fetch registry from Eureka
eureka.client.fetch-registry=true


# ---------------------------------------------------------
# CONFIG SERVER SETTINGS
# ---------------------------------------------------------

# Activate native profile (we are NOT using Git for now)
spring.profiles.active=native

# Location of configuration files
# "classpath:/config" means we will create a folder inside resources
spring.cloud.config.server.native.search-locations=classpath:/config

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}